# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_yape_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'GoogleSignIn'
  pod 'Toast-Swift', '~> 5.0.1'

  target 'test_yape_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test_yape_iosUITests' do
    # Pods for testing
  end

end
