# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'test_yape_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'GoogleSignIn'
  pod 'FirebaseUI'
  pod 'FirebaseUI/Auth'
  pod 'GoogleSignIn'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/OAuth' # Used for Sign in with Apple, Twitter, etc
  pod 'FirebaseUI/Phone'
  # Pods for test_yape_ios

  target 'test_yape_iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'test_yape_iosUITests' do
    # Pods for testing
  end

end
